### ISSUE TITLE
How to preload the font. Did not display some words of the buttons  after the start of the time cycle

### ISSUE THREAD

**Issue by wu1274704958** [TankOs/SFGUI#58]
How to preload the font. Did not display some words of the buttons  after the start of the time cycle

**Comment by eXpl0it3r** [comment]
Preload as in? I think you're just jumping to conclusions that because the font isn't rendered correctly the font wasn't loaded or so.

If you got displaying issues with the font, it's probably because the `SFGUI` object wasn't created correctly. Check the examples, they'll run correctly and see how you can adapt that code for your code base.
